"""Generate a Kotlin constants file with the trained symptom and fusion
LogisticRegression weights (Task 16), so the on-device app can run these
two trivial linear models with no ML runtime -- just a dot product and a
sigmoid, ported directly rather than routed through ONNX Runtime.

Usage:
    .venv/Scripts/python.exe -m src.export.export_logreg_kotlin
"""

import joblib

from src.common.config import MODELS_DIR
from src.symptom.labeling import SYMPTOM_COLUMNS

OUT_PATH = (
    MODELS_DIR.parent
    / "android_app"
    / "app"
    / "src"
    / "main"
    / "java"
    / "com"
    / "kongu"
    / "ai4tb"
    / "wrapper"
    / "ModelWeights.kt"
)

FUSION_FEATURES = ["p_xray", "p_cough", "p_symptom"]


def kotlin_double_array(values) -> str:
    return "doubleArrayOf(" + ", ".join(f"{v:.10f}" for v in values) + ")"


def main():
    symptom_model = joblib.load(MODELS_DIR / "symptom" / "logreg.pkl")
    fusion_model = joblib.load(MODELS_DIR / "fusion" / "logreg.pkl")

    symptom_weights = symptom_model.coef_[0].tolist()
    symptom_intercept = float(symptom_model.intercept_[0])
    fusion_weights = fusion_model.coef_[0].tolist()
    fusion_intercept = float(fusion_model.intercept_[0])

    kotlin_symptom_labels = ", ".join(f'"{c}"' for c in SYMPTOM_COLUMNS)

    content = f'''package com.kongu.ai4tb.wrapper

import kotlin.math.exp

/**
 * Trained logistic regression weights for the symptom and fusion models,
 * ported directly from the Python training pipeline (src/symptom/train.py,
 * src/fusion/train.py) -- generated by
 * src/export/export_logreg_kotlin.py, not hand-written. Regenerate that
 * script's output rather than editing these arrays by hand if the
 * underlying models are retrained.
 *
 * Both models are a simple dot product + sigmoid, so no ML runtime
 * (ONNX Runtime etc.) is needed for these two, unlike the X-ray/cough
 * CNNs.
 */
object ModelWeights {{

    // Order matches src/symptom/labeling.py SYMPTOM_COLUMNS exactly --
    // the UI checklist order below must follow this same order.
    val symptomLabels: List<String> = listOf({kotlin_symptom_labels})

    private val symptomWeights: DoubleArray = {kotlin_double_array(symptom_weights)}
    private const val symptomIntercept: Double = {symptom_intercept:.10f}

    // Order: p_xray, p_cough, p_symptom -- matches src/fusion/train.py FEATURES.
    private val fusionWeights: DoubleArray = {kotlin_double_array(fusion_weights)}
    private const val fusionIntercept: Double = {fusion_intercept:.10f}

    private fun sigmoid(z: Double): Double = 1.0 / (1.0 + exp(-z))

    /** symptomsPresent: same order/length as [symptomLabels], 1.0 if checked else 0.0. */
    fun predictSymptomProbability(symptomsPresent: DoubleArray): Double {{
        require(symptomsPresent.size == symptomWeights.size)
        var z = symptomIntercept
        for (i in symptomWeights.indices) {{
            z += symptomWeights[i] * symptomsPresent[i]
        }}
        return sigmoid(z)
    }}

    fun predictFusedProbability(pXray: Double, pCough: Double, pSymptom: Double): Double {{
        val z = fusionIntercept +
            fusionWeights[0] * pXray +
            fusionWeights[1] * pCough +
            fusionWeights[2] * pSymptom
        return sigmoid(z)
    }}
}}
'''

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    print(f"Symptom weights: {len(symptom_weights)} features, intercept={symptom_intercept:.4f}")
    print(f"Fusion weights: {fusion_weights}, intercept={fusion_intercept:.4f}")


if __name__ == "__main__":
    main()
