package com.kongu.ai4tb.wrapper

import kotlin.math.exp

/**
 * Trained logistic regression weights for the symptom and fusion models,
 * ported directly from the Python training pipeline (src/symptom/train.py,
 * src/fusion/train.py) -- generated by
 * src/export/export_logreg_kotlin.py, not hand-written. Regenerate that
 * script's output rather than editing these arrays by hand if the
 * underlying models are retrained.
 *
 * Both models are a simple dot product + sigmoid, so no ML runtime
 * (ONNX Runtime etc.) is needed for these two, unlike the X-ray/cough
 * CNNs.
 */
object ModelWeights {

    // Order matches src/symptom/labeling.py SYMPTOM_COLUMNS exactly --
    // the UI checklist order below must follow this same order.
    val symptomLabels: List<String> = listOf("fever for two weeks", "coughing blood", "sputum mixed with blood", "night sweats", "chest pain", "back pain in certain parts", "shortness of breath", "weight loss", "body feels tired", "lumps that appear around the armpits and neck", "cough and phlegm continuously for two weeks to four weeks", "swollen lymph nodes", "loss of appetite")

    private val symptomWeights: DoubleArray = doubleArrayOf(5.2796149068, 0.7060787815, 0.7952058995, 0.6797031907, -0.0681393477, -0.0539916940, 0.2321158149, 0.6475304390, 0.1457397190, -0.0327372159, 6.2786729650, -0.0661587512, -0.1812916891)
    private const val symptomIntercept: Double = -4.2479952351

    // Order: p_xray, p_cough, p_symptom -- matches src/fusion/train.py FEATURES.
    private val fusionWeights: DoubleArray = doubleArrayOf(2.4409544397, 1.8625728926, 2.8013009349)
    private const val fusionIntercept: Double = -3.7031696399

    private fun sigmoid(z: Double): Double = 1.0 / (1.0 + exp(-z))

    /** symptomsPresent: same order/length as [symptomLabels], 1.0 if checked else 0.0. */
    fun predictSymptomProbability(symptomsPresent: DoubleArray): Double {
        require(symptomsPresent.size == symptomWeights.size)
        var z = symptomIntercept
        for (i in symptomWeights.indices) {
            z += symptomWeights[i] * symptomsPresent[i]
        }
        return sigmoid(z)
    }

    fun predictFusedProbability(pXray: Double, pCough: Double, pSymptom: Double): Double {
        val z = fusionIntercept +
            fusionWeights[0] * pXray +
            fusionWeights[1] * pCough +
            fusionWeights[2] * pSymptom
        return sigmoid(z)
    }
}
